apps/ranking/urls.py
from django.conf.urls.defaults import *

from ranking.models import Deputado

info_dict = {
    'queryset': Deputado.objects.all(),
}


urlpatterns = patterns('',
    #url(r"^$", view='ranking.views.index', name='ranking_index'),
    #url(r'^(?P<slug>[-\w]+)/$', view='django.views.generic.list_detail.object_detail', dict(slug_field='slug')),
    url(r'^(?P<slug>[-\w]+)/$', 'django.views.generic.list_detail.object_detail', dict(info_dict), 'ranking_deputado_detail'),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()


handler500 = "pinax.views.server_error"


urlpatterns = patterns("",
    url(r"^$", view='ranking.views.index', name='ranking_index'),
    url(r'^sobre/$', direct_to_template, {"template": "sobre.html"}, name="sobre"),
    url(r"^r/", include('ranking.urls')),
    url(r"^admin/", include(admin.site.urls)),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )

apps/ranking/models.py
# -*- coding: utf-8 -*-
from datetime import date
from django.db import models
from autoslug import AutoSlugField
from serializeddatafield import SerializedDataField


class VotoManager(models.Manager):
    
    def get_for_user_in_bulk(self, user):
        votos_dict = {}
        votos = list(self.filter(deputado__pk=user.id, voto_int__isnull=False))
        votos_dict = dict([(voto.proposicao, voto) for voto in votos])
        return votos_dict
        

class Deputado(models.Model):
    
    nome = models.CharField(blank=True, max_length=80)
    slug = AutoSlugField(populate_from='nome', unique=True)
    data_nascimento = models.DateField(blank=True, null=True)
    municipio_nascimento = models.CharField(blank=True, max_length=150)
    nacionalidade = models.CharField(blank=True, max_length=150)
    instrucao = models.CharField(blank=True, max_length=80)
    ocupacao = models.CharField(blank=True, max_length=80)
    votos_ultima_eleicao = models.CharField(blank=True, max_length=80)
    foto = models.ImageField(blank=True, upload_to="uploads/MODELNAME/%Y/%m/%d")
    vota_com = SerializedDataField(null=True, blank=True)
    
    
    @property
    def total_de_presencas(self):
        return Presenca.objects.filter(deputado=self, presenca="Presente").count()
    
    # Total de sessoes realizadas durante o seu mandato     
    @property
    def total_de_sessoes(self):
        return Presenca.objects.filter(deputado=self).count()
    
    @property    
    def porcentagem_de_presencas(self):
        return int((self.total_de_presencas * 100 ) / self.total_de_sessoes)
    
    @property
    def idade(self):
        dias_no_ano = 365.25
        return int((date.today() - self.data_nascimento).days/dias_no_ano)
    
    class Meta:
        pass

    def __unicode__(self):
        return self.nome

    def get_absolute_url(self):
        raise NotImplementedError        
        
class Sessao(models.Model):
    
    numero = models.CharField(blank=True, max_length=80)
    data = models.DateField(blank=True, null=True)
    id_externo = models.IntegerField(blank=True, null=True)
    
    class Meta:
        ordering = ['-data']

    def __unicode__(self):
        return "Sessao numero %s" % self.numero

    def get_absolute_url(self):
        raise NotImplementedError

        
class Presenca(models.Model):
    
    sessao = models.ForeignKey(Sessao, blank=True, null=True)
    deputado = models.ForeignKey(Deputado, blank=True, null=True)
    presenca = models.CharField(blank=True, max_length=80)
    justificativa = models.CharField(blank=True, max_length=200)
    
    class Meta:
        ordering = ['-sessao']

    def __unicode__(self):
        return "Sessao numero %s - Dep. %s" % (self.sessao.numero, self.deputado.nome)

    def get_absolute_url(self):
        raise NotImplementedError

class Proposicao(models.Model):
    """
    
    """
    
    codigo = models.CharField(blank=True, max_length=80)
    sessao = models.ForeignKey(Sessao, blank=True, null=True)
    url = models.URLField(blank=True)
    descricao = models.TextField(blank=True)
    
    class Meta:
        pass

    def __unicode__(self):
        return self.codigo

    def get_absolute_url(self):
        raise NotImplementedError

class Voto(models.Model):
    """
    
    """
    
    proposicao = models.ForeignKey(Proposicao, blank=True, null=True)
    deputado = models.ForeignKey(Deputado, blank=True, null=True)
    voto = models.CharField(blank=True, max_length=80)
    voto_int = models.SmallIntegerField(blank=True, null=True)
    
    objects = VotoManager()
    
    class Meta:
        pass

    def __unicode__(self):
        return "Dep. %s: %s" % (self.deputado.nome, self.voto)

    def get_absolute_url(self):
        raise NotImplementedError
        
    def save(self, *args, **kwargs):
        if not self.id:
            if self.voto == u'Sim':
                self.voto_int = 1
            elif self.voto == u'Não':
                self.voto_int = -1
        super(Voto, self).save()

apps/ranking/views.py
from annoying.decorators import render_to

from ranking.models import Deputado


@render_to('ranking/index.html')
def index(request):
    ranking = sorted(Deputado.objects.all(), key=lambda d: d.porcentagem_de_presencas)
    return {'ranking': ranking}

templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <title>{% block head_title_base %}{% if SITE_NAME %}{{ SITE_NAME }} : {% endif %}{% block head_title %}{% endblock %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}bootstrap-1.1.1.css" rel="stylesheet">
    
    <!-- Le scripts -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    
    <!-- Le fav and touch icons 
    <link rel="shortcut icon" href="images/favicon.ico">-->
    {% block extra_head_base %}
        {% block extra_head %}{% endblock %}
    {% endblock %}
  </head>

  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <h3><a href="/">Assembl&eacute;iaAberta</a></h3>
          <ul>
            <li class="active"><a href="/">In&iacute;cio</a></li>
            <li><a href="#codigo_fonte">C&oacute;digo Fonte</a></li>
            <li><a href="#api">API</a></li>
            <li><a href="#sobre">Sobre</a></li>
          </ul>
        </div>
      </div>
    </div>
    
    
        {% block body %}
        {% endblock %}
  
      {% block footer %}
      <div class="container">
          <footer>
            <p>AssembléiaAberta 2011</p>
          </footer>
      </div>
      {% endblock %}

    

  {% block extra_body %}{% endblock %}
  </body>
</html>

templates/ranking/_dados_pessoais.html
<p>Idade: {{ object.idade }}</p>
<p>Data de Nascimento: {{ object.municipio_nascimento }}</p>
<p>Nacionalidade: {{ object.nacionalidade }}</p>
<p>Instru&ccedil;&atilde;o: {{ object.instrucao }}</p>

templates/ranking/_presenca.html
<table class="zebra-striped">
    <tr>
        <th>Sess&atilde;o</th>
        <th>Presen&ccedil;a</th>
    </tr>
	{% for presenca in object.presenca_set.all %}
		<tr>
			<td>{{ presenca.sessao.numero }}&ordf;</td>
			<td>
    			{% if presenca.justificativa %}
    			    <a href="#" original-title="{{ presenca.justificativa }}" class="tipsy">{{ presenca.presenca }}</a>
    			{% else %}
    			    {{ presenca.presenca }}
    			{% endif %}
			</td>
		</tr>	
{% endfor %}
</table>

templates/ranking/_votos.html
<table class="zebra-striped">
    <tr>
        <th>Proposi&ccedil;&atilde;o</th>
        <th>Data da Vota&ccedil;&atilde;o</th>
        <th>Voto</th>
    </tr>
	{% for voto in object.voto_set.all %}
		<tr>
			<td>{{ voto.proposicao.codigo }}</td>
			<td>{{ voto.proposicao.sessao.data|date:"d\/m\/Y" }}</td>
			<td>{{ voto.voto }}</td>
		</tr>	
{% endfor %}
</table>

templates/ranking/deputado_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{{ object.nome }}{% endblock %}

{% block extra_head %}
<link href="{{ STATIC_URL }}css/tipsy.css" rel="stylesheet">
<script src="{{ STATIC_URL }}js/tabs.js"></script>
<script src="{{ STATIC_URL }}js/jquery.tipsy.js"></script>
<script type='text/javascript'>
  $(function() {
    $('.tipsy').tipsy({gravity: 'w'});
  });
</script>

{% endblock %}

{% block body %}
    <div class="container" style="margin-top:60px;">        
        <div class="page-header"><h1>{{ object.nome }}</h1></div>

        <div class="row">
            <div class="span4 columns">
                <p><img src={{ object.foto }}></p>
                <h4>&Uacute;ltimas elei&ccedil;&otilde;es</h4>
            	<p>{{ object.votos_ultima_eleicao }}</p>
            	<h4>Assiduidade</h4>
            	<p>{{ object.porcentagem_de_presencas }}%</p>
            	<h4>Vota com</h4>
            	<ul>
            	    {% for i,v in object.vota_com %}
            	    <li>{{ v }} - {{ i }}%</li>
            	    {% empty %}
            	    <li>Dados insuficientes</li>
            	    {% endfor %}
            	</ul>
            </div>
    
            <div class="span12 columns">
            	<ul class="pills">
                  <li class="active"><a href="#dados_pessoais">Dados Pessoais</a></li>
                  <li><a href="#votos">Votos</a></li>
                  <li><a href="#presenca">Presenca Plen&aacute;ria</a></li>
                </ul>

            	<ul class="tabs-content">
            	    <li class="active" id="dados_pessoais">
            	        {% include "ranking/_dados_pessoais.html" %}
            	    </li>
            	    <li id="votos">
            	        {% include "ranking/_votos.html" %}
                    </li>
                    <li id="presenca">
                        {% include "ranking/_presenca.html"%}
                    </li>
            	</ul>
            </div>
        </div> <!-- /row -->
    	
    </div> <!-- /container -->

{% endblock %}

templates/ranking/index.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}Assembl&eacute;ia Aberta{% endblock %}

{% block body %}
    
    <!-- Masthead (blueprinty thing)
    ================================================== -->
    <div id="masthead">
      <div class="inner">
        <div class="container">
          <h1>Tornando a Assembl&eacute;ia Verdadeiramente Transparente</h1>
          <p class="lead">
            O Assembl&eacute;iaAberta ajuda a tornar a informa&ccedil;&atilde;o legislativa mais acess&iacute;vel e transparente<br />
            atrav&eacute;s da divulga&ccedil;&atilde;o e an&aacute;lise de dados oficiais do governo.<br />
          </p>
          <p><strong>Ah:</strong> tamb&eacute;m temos um ranking que n&atilde;o vai sair do ar!</p>
        </div><!-- /container -->
      </div>
    </div>
    
    <div class="container">
        <section id="ranking">
            <div class="page-header">
                <h1>Ranking de Assiduidade</h1>
            </div>
            <div class="row">
                <div class="span4 columns">
                    <h2>Ordem inversa</h2>
                    <p>A assiduidade &eacute; calculada relativamente ao n&uacute;mero de sess&otilde;es desde o in&iacute;cio do mandato.</p>
                    <p>Por exemplo, um deputado que compareceu a 44 sess&otilde;es de 55 desde o princ&iacute;pio de seu mandato, ter&aacute; uma assiduidade de 80%.<p>
                    <p>Portanto, <strong>o n&uacute;mero 1 do ranking &eacute; o mais faltoso </strong>e o &uacute;ltimo &eacute; o mais ass&iacute;duo.</p>
                </div>
                <div class="span12 columns">
                    <table class="zebra-striped">
                        <tr>
                            <th>Posi&ccedil;&atilde;o</th>
                            <th>Nome</th>
                            <th>Assiduidade</th>
                        </tr>
                        {% for d in ranking %}
                    		<tr>
                    			<td>{{ forloop.counter }}.&nbsp;</td>
                    			<td><a href={% url ranking_deputado_detail d.slug %}>{{ d }}</a></td>
                    			<td>{{ d.porcentagem_de_presencas }}%</td>
                    		</tr>	
                    	{% endfor %}
                    </table>
                </div>
            </div> <!--/row -->
        </section>
        
        <section id="sobre">
            <div class="page-header">
                <h1>Sobre</h1>
            </div>
            <div class="row">
                <div class="span6 columns">
                    <h3>O que é?</h3>
                    <p>O objetivo do AssembléiaAberta é apresentar a informação legislativa da Alesc de forma realista e transparente, através da divulgação e análise de dados oficiais do governo.</p>
                    <p>O site é inspirado no <a href="http://www.opencongress.org">OpenCongress</a>, <a href="http://www.govtrack.us">GovtTrack</a> e, claro no <a href="http://www.deputadometro.com.br">Deputadômetro</a> .
                </div>
                <div class="span5 columns">
                    <h3>Como?</h3>
                    <p>Além do ranking (inverso) de assiduidade, o site também disponibiliza histórico de votação e histórico de presença plenária (com as justificativas) por deputado, e a correlação de votos: o cálculo da frequencia com que os deputados votam juntos. Abaixo da foto de cada deputado estão listados os colegas cujos votos estão correlacionados mais fortemente.</p>  
                    <p>O código fonte justamente com as instruções de como colocá-lo online estão disponíveis no Github (a idéia é permitir que qualquer cidadão possa colocar seu próprio "deputadômetro" no ar) está disponível e os dados por trás do site para quem quiser construir um site ou ferramenta superior para analisá-los</p>
                    <p>O processo de coleta dos dados é todo automatizado; um robô diariamente acessa o site da Alesc e coleta os dados oficiais.</p>
                </div>
                <div class="span5 columns">
                    <h3>Quem criou?</h3>
                     <p>Meu nome é Rodrigo Landerdahl (<a href="http://http://twitter.com/#!/rlander">@rlander</a> no twitter) e, como muitos catarinenses, fiquei frustrado com a retirada do ar do ranking do site deputadômetro. Por isso, decidi colocar a mão na massa, perder algumas noites de sono, e fazer uma alternativa.</p>
                </div>
            </div>
        </section>
	
	</div> <!-- /container -->
 
{% endblock %}

templates/sobre.html
{% extends "base.html" %}

{% block head_title %}Sobre{% endblock %}

{% block body %}
    <div class="container" style="margin-top:60px;">     
        <section id="sobre">
            <div class="page-header">
                <h1>Sobre o site</h1>
            </div>

        </section>
	
	</div> <!-- /container -->
 
{% endblock %}